# Generated by Django 2.2.4 on 2019-09-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('status', models.CharField(default='new', max_length=40, verbose_name='Status')),
                ('date', models.CharField(max_length=10, verbose_name='Date')),
            ],
        ),
    ]
