# Generated by Django 2.2.4 on 2019-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190905_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.TextField(max_length=10, verbose_name='Date'),
        ),
    ]
