# Generated by Django 2.2.4 on 2019-09-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190905_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
