# Generated by Django 2.2.5 on 2019-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='details',
            field=models.TextField(max_length=400, null=True, verbose_name='Details'),
        ),
    ]
