# Generated by Django 2.2.5 on 2019-09-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_todo_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(max_length=10, null=True, verbose_name='Date'),
        ),
    ]
